version: "3.8"

services:
  database:
    image: postgres:12.8
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=enterprise-command-db
    ports:
      - 5432:5432
    volumes:
      - enterprise-command-db:/var/lib/postgresql/data
volumes:
  enterprise-command-db: